networks:
  net_internet: {}
  net_cloud:
    internal: true
  net_onprem:
    internal: true

services:
  edge:
    container_name: edge
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./edge/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api/certs/api:/etc/nginx/certs/api:ro
    depends_on: [api, ws]
    networks: [net_internet, net_cloud]

  api:
    container_name: api
    build: ./api
    environment:
      - APP_ENV=local
    networks: [net_internet, net_cloud]


  ws:
    container_name: ws
    build: ./ws
    environment:
      - PORT=8080
    networks: [net_cloud]

  bridge:
    container_name: bridge
    build: ./bridge
    volumes:
      - ./api/certs/ca/ca.crt:/etc/ssl/certs/hococo_ca.crt:ro

    networks: [net_onprem, net_internet]

  salto:
    container_name: salto
    image: ealen/echo-server
    environment: [LOG=1]
    networks: [net_onprem]
