networks:
  net_internet: {}
  net_cloud:
    internal: true
  net_onprem:
    internal: true

volumes:
  crl-data: {}

services:
  edge:
    container_name: edge
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./edge/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api/certs/api:/etc/nginx/certs/api:ro
      - ./api/certs/ws:/etc/nginx/certs/ws:ro
      - ./api/certs/ca/ca.crt:/etc/nginx/certs/ca/hococo_ca.crt:ro
      - crl-data:/etc/nginx/crl:ro
    depends_on: [api, ws]
    networks:
      net_internet:
        aliases:
          - api.hococo.internal
          - ws.hococo.internal
      net_cloud:
        aliases:
          - api.hococo.internal
          - ws.hococo.internal
    environment:
      - WS_ADMIN_URL=https://ws.hococo.internal:9443/admin/ws
      - WS_ADMIN_CERT=/app/certs/api/api-client.crt
      - WS_ADMIN_KEY=/app/certs/api/api-client.key
      - WS_ADMIN_CA=/app/certs/ca/ca.crt

    command: >
      sh -c "
        ( while :; do
            sleep 60;
            nginx -s reload || true;
          done ) &
        nginx -g 'daemon off;'
      "

  api:
    container_name: api
    build: ./api
    environment:
      - APP_ENV=local
      - CA_DIR=/app/certs/ca
      - BRIDGE_CRL_PATH=/var/lib/hococo-crl/bridge.crl.pem

    volumes:
      - crl-data:/var/lib/hococo-crl
    networks: [net_internet, net_cloud]

  ws:
    container_name: ws
    build: ./ws
    environment:
      - PORT=8080
    networks: [net_cloud]

  bridge:
    container_name: bridge
    build: ./bridge
    environment:
      - BRIDGE_API_CA_PATH=/etc/ssl/certs/hococo_ca.crt
      - BRIDGE_STATE_DIR=/var/lib/hococo-bridge
    volumes:
      - ./api/certs/ca/ca.crt:/etc/ssl/certs/hococo_ca.crt:ro
    ports:
      - "18080:8080"
    networks: [net_onprem, net_internet]

  admin:
    container_name: admin
    build: ./admin
    ports:
      - "3000:80"
    networks: [net_internet]
