events {}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://api:80/;
      proxy_set_header Host $host;
    }

    location /ws/ {
      proxy_pass http://ws:8080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 600s;
      proxy_send_timeout 600s;
    }
  }
}
